# Generated by Django 6.0.2 on 2026-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_soil_moisture_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaCelda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celda_id', models.CharField(max_length=20, unique=True)),
                ('anio_inicio', models.IntegerField()),
                ('anio_fin', models.IntegerField()),
                ('modelo', models.CharField(max_length=30)),
                ('resumen', models.JSONField()),
                ('calculado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
